# Generated by Django 5.0.2 on 2024-02-28 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.tech'),
        ),
    ]
