# Generated by Django 5.0.2 on 2024-02-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_tech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tech',
            field=models.CharField(max_length=200),
        ),
    ]
