# Generated by Django 5.0.2 on 2024-02-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_tech'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tech',
        ),
        migrations.AddField(
            model_name='project',
            name='techs',
            field=models.ManyToManyField(to='projects.tech'),
        ),
    ]
